[api]
gemini_api_key = "AIzaSyBta3wFAXaEEHzRVTdT1kwypeAKt23-nbk"
vertexai_project = "mutelu-chat"

[gcs]
type = "service_account"
project_id = "mutelu-worldth"
private_key_id = "4019e992775904ebd0dc756490dc30c6aea776cd"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDvtPAelwFqqMkg
pkQL4oQUbHKQ7D51duGRgfztJf8jRZEjdwg31OXkZJx3d8tbLkot0tsCpvmRU36U
0HO9YyetoVxjZMg+ghzZESmgV5/PEWyyMjx/9IcSQmwlUNckPX2pW0J2/SD1Gonf
nGp+s2VnIbAPycQbVyh414IsZ3lhLdHgb7T4B0XaQ28xAqBkpTs3LC27XAN8bFiu
qiIqu0HUaDio0DKXJGgggPWZdMpGuoOMJZr5Jc/MsUPNgESQ/mLP9b8KnEqJT+x2
vHj5DNw1pJXzYsHQM0WuAk7yC8lmLEP6KK4Scaq9GTFtWuII59kz9L+Ir6hD0BHr
QKwXB4y5AgMBAAECggEAE/v5+BYcBSA03HPGjby0L3iD692P4eUn+ySWL9AQjFVB
bqGyERpYkqKctNnk6ofA1KWVCSYrylgZ4B6pqsSe5NSxSiWqpPBEc9Uz3jocvBVQ
AmJtaGsiuhZiXV4Qm0t3gLlEbX0lbhA1v56S9lgCGgeh93IzCk1JT4HQFXmiK5Eo
CqXB0HIsps9l+NQ9IWXQJFR79as5qvetXNsSTahGI4GZHTeCZ0oYgshsmSElL75P
xN/y+CvmFj04wD4x0c3bzvanO+Q0N7tu1H2arzmCXgtf/eiQiSUTv4WrEYvo9GZh
1Rv+VNJ94a8aacdpcvR408zRAo+7uuf50LzCpx3QzQKBgQD/AuKZv3/4vWZ66+VP
+GyiQtrgliue/vW+x2eL1YceNnq3/R7ErRnQV13RLPn+NtgxCqEyP5sF1Dk7dqTQ
60TQbfi7cAyEZbD+EjwnJ/Di2oNq24qvka99UFrHnM5BRRYDME41QtPH+F5z4hp0
/+cERQ+VhyJQ6CHOUhhqdhnhywKBgQDwoty1Rq3NFw0G7QdepVarzTi1UBucc+Er
OBAIqzzdDlLdgZRqoAkov26kuJnf4IdrqsVr4Ifczwke4eAH98pYStbzPFFqcJcG
KRH6352Sd5T4d+V89nZcAJexRp0Uqrflta+xROZyu5MujTMZcKqX6q+GfLlhKt9v
p4FJ2kFrCwKBgQDLOX1kkZxmmmoFI+FHbe8FEMplmMeCmiU1uKvoYG6hwUDjR7Ex
g9HCmx2FCZbg5Mw9qP71kIL2jj5eCRsn85aPlFRY697N1EzM7bNKcSYjY4i/q95G
NI/qChOOaIRmt6vnNqPdBjjIcEK1j0cOXrG4UWEuBNdwKs5mIj6a+St/KQKBgGG9
FL5Abfl+YlkszzB/IXv4iA8E8aITYyLFy6Vpv/fdiITVy+2fAPle/9bB8CYBsZ9m
pndRpH1oTkEP54n0+GfyRepX1o3QG1dyOQ5X402JaqWdNUYTaTGnP/XOQ6EQUk9o
A2uSG7QAQiDHUzkDDRdVSGPspvMzkbttItNXZfjPAoGAOeIksKfAsJNf2A+Qwd9j
Fp5tO1SXKfEKkOBQZ0m2VME2MuXTIlyn279kCoNxnqrngog3scptp0n5gnuh3L5l
6FKiYw62YfuWQ5K4Je4HeyWZ2MRZIgNTj/3hlaCJieC+w2oW5oIZC8SsiDjXSPNS
vMxHLZKICxjBMpurzAUocHs=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-flk5n@mutelu-worldth.iam.gserviceaccount.com"
client_id = "107062814008138458175"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-flk5n@mutelu-worldth.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
bucket_name = "mutelu_bucket"

